Name=input("Enter your name:")
Age=int(input("enter your age:"))
Roll_no=int(input("enter your roll_no:"))
Weight=float(input("enter your weight:"))
print("name:",Name)
print("age:",Age)
print("roll_no:",Roll_no)
print("weight:",Weight)